[package]
name = "lib3d6"
version = "0.0.4"
authors = ["George <george@cerebralab.com>"]
description = "Potentially my personal utility library, for now a test"
license = "MIT"
edition = "2018"
documentation = "https://github.com/George3d6/lib3d6"

[lib]
proc-macro = true